package uk.co.iteratively.amm.models

import com.fasterxml.jackson.annotation.JsonAlias
import com.fasterxml.jackson.annotation.JsonProperty
import uk.co.iteratively.amm.AndroidApi
import uk.co.iteratively.amm.annotations.Since

@Since(AndroidApi.ANDROID_1)
data class Application(@JsonAlias("android:allowTaskReparenting") var allowTaskReparenting: Boolean = false,
                       @JsonAlias("android:allowBackup") var allowBackup: Boolean = true,
                       @JsonAlias("android:allowClearUserData") var allowClearUserData: Boolean = true,
                       @JsonAlias("android:backupAgent") var backupAgent: String = "",
                       @JsonAlias("android:backupInForeground") var backupInForeground: Boolean = false,
                       @JsonAlias("android:banner") var banner: String = "",
                       @JsonAlias("android:debuggable") var debuggable: Boolean = false,
                       @JsonAlias("android:description") var description: String = "",
                       @JsonAlias("android:directBootAware") var directBootAware: Boolean = false,
                       @JsonAlias("android:enabled") var enabled: Boolean = true,
                       @JsonAlias("android:extractNativeLibs") var extractNativeLibs: Boolean = true,
                       @JsonAlias("android:fullBackupContent") var fullBackupContent: String = "",
                       @JsonAlias("android:fullBackupOnly") var fullBackupOnly: Boolean = false,
                       @JsonAlias("android:hasCode") var hasCode: Boolean = true,
                       @JsonAlias("android:hasFragileUserData") var hasFragileUserData: Boolean = false,
                       @JsonAlias("android:hardwareAccelerated") var hardwareAccelerated: Boolean?,
                       @JsonAlias("android:icon") var icon: String = "",
                       @JsonAlias("android:isGame") var isGame: Boolean = false,
                       @JsonAlias("android:killAfterRestore") var killAfterRestore: Boolean = false,
                       @JsonAlias("android:largeHeap") var largeHeap: Boolean,
                       @JsonAlias("android:label") var label: String = "",
                       @JsonAlias("android:logo") var logo: String = "",
                       @JsonAlias("android:manageSpaceActivity") var manageSpaceActivity: String = "",
                       @JsonAlias("android:name") var name: String,
                       @JsonAlias("android:networkSecurityConfig") @Since(AndroidApi.NOUGAT) var networkSecurityConfig: String = "",
                       @JsonAlias("android:permission") var permission: String = "",
                       @JsonAlias("android:persistent") var persistent: Boolean = false,
                       @JsonAlias("android:process") var process: String = "",
                       @JsonAlias("android:restoreAnyVersion") var restoreAnyVersion: Boolean = false,
                       @JsonAlias("android:requestLegacyExternalStorage") var requestLegacyExternalStorage: Boolean?,
                       @JsonAlias("android:requiredAccountType") @Since(AndroidApi.JELLY_BEAN_MR2) var requiredAccountType: String = "",
                       @JsonAlias("android:resizeableActivity") @Since(AndroidApi.NOUGAT) var resizeableActivity: Boolean?,
                       @JsonAlias("android:restrictedAccountType") @Since(AndroidApi.JELLY_BEAN_MR2) var restrictedAccountType: String = "",
                       @JsonAlias("android:supportsRtl") @Since(AndroidApi.JELLY_BEAN_MR1) var supportsRtl: Boolean = false,
                       @JsonAlias("android:taskAffinity") var taskAffinity: String = "",
                       @JsonAlias("android:testOnly") var testOnly: Boolean?,
                       @JsonAlias("android:theme") var theme: String = "",
                       @JsonAlias("android:uiOptions") @Since(AndroidApi.ICE_CREAM_SANDWICH) var uiOptions: UIOptions = UIOptions.none,
                       @JsonAlias("android:usesCleartextTraffic") @Since(AndroidApi.MARSHMALLOW) var usesCleartextTraffic: Boolean?,
                       @JsonAlias("android:vmSafeMode") @Since(AndroidApi.FROYO) var vmSafeMode: Boolean?,
                       @set:JsonProperty("activity") var activities: Set<Activity> = setOf(),
                       @set:JsonProperty("activity-alias") var activityAliases: Set<ActivityAlias> = setOf(),
                       @set:JsonProperty("meta-data") var metaData: Set<MetaData> = setOf(),
                       @set:JsonProperty("instrumentation") var instrumentation: Set<Instrumentation> = setOf(),
                       @set:JsonProperty("provider") var providers: Set<Provider> = setOf(),
                       @set:JsonProperty("receiver") var receivers: Set<Receiver> = setOf(),
                       @set:JsonProperty("service") var services: Set<Service> = setOf(),
                       @set:JsonProperty("supports-gl-texture") var supportsGlTextures: Set<SupportsGLTexture> = setOf(),
                       @set:JsonProperty("") var usesLibraries: Set<UsesLibrary> = setOf())
